apiVersion: v1
kind: Service
metadata:
  name: amqp-proxy
  labels:
    app: amqp-proxy
  {{- include "amqp-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.amqpProxy.type }}
  selector:
    app: amqp-proxy
  {{- include "amqp-proxy.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.amqpProxy.ports | toYaml | nindent 2 -}}
